In [1]:
import pandas as pd

In [5]:
# data frame is a table
# rows → index
# data → cells

students_data = [['Kamel', 23, 'Alex'], ['Samir', 23, 'Cairo']]
rows = ['student_1', 'student_2']
columns = ['Name', 'Age', 'Address']

df_1 = pd.DataFrame(data=students_data, index=rows, columns=columns)

In [6]:
df_1

            Name  Age Address
student_1  Kamel   23    Alex
student_2  Samir   23   Cairo

In [7]:
df_1.reset_index()

       index   Name  Age Address
0  student_1  Kamel   23    Alex
1  student_2  Samir   23   Cairo

In [27]:
import numpy as np
from numpy.random import randn

In [28]:
np.random.seed(150000) # return the same random array each time.
df = pd.DataFrame(index=['X', 'Y', 'Z'], columns=['C1', 'C2', 'C3'], data = randn(3, 3) )
df

         C1        C2        C3
X  0.924685  0.554093 -1.384913
Y -1.168588  0.236403  0.395286
Z -1.476801 -0.187689  1.377000

In [29]:
# Printing columns
df[ ['C1', 'C3'] ]

         C1        C3
X  0.924685 -1.384913
Y -1.168588  0.395286
Z -1.476801  1.377000

In [42]:
df['Sum'] = df['C1'] + df['C2'] + df['C3']

In [31]:
df

         C1        C2        C3       Sum
X  0.924685  0.554093 -1.384913  0.093865
Y -1.168588  0.236403  0.395286 -0.536899
Z -1.476801 -0.187689  1.377000 -0.287490

In [33]:
# Printing rows
df.loc[['X', 'Y']]

         C1        C2        C3       Sum
X  0.924685  0.554093 -1.384913  0.093865
Y -1.168588  0.236403  0.395286 -0.536899

In [34]:
df.loc[ ['X', 'Y'], ['C2', 'C3'] ]

         C2        C3
X  0.554093 -1.384913
Y  0.236403  0.395286

In [35]:
# Printing cells

In [37]:
df.loc['X', 'C2']

np.float64(0.5540930211676844)

In [43]:
# Droping columns[axis → 1] 
df.drop('Sum', axis=1, inplace=True)

In [50]:
# Droping rows[axis → 0]
df.drop('Z', axis=0, inplace=True)

In [54]:
df

         C1        C2        C3
X  0.924685  0.554093 -1.384913
Y -1.168588  0.236403  0.395286

In [62]:
# Filtering the data
df_2 = df[ (df['C3'] >= 0) | (df['C1'] >= .5)].loc['Y']

In [63]:
df_2

C1   -1.168588
C2    0.236403
C3    0.395286
Name: Y, dtype: float64

In [64]:
# Cleaning the data

In [67]:
data = [ [np.nan, 23, 107], [78, np.nan, 88], [44, np.nan, 67] ]
rows = ['A', 'B', 'C']
columns = ['C1', 'C2', 'C3']

df_3 = pd.DataFrame(data=data, index=rows, columns=columns)

In [68]:
df_3

     C1    C2   C3
A   NaN  23.0  107
B  78.0   NaN   88
C  44.0   NaN   67

In [70]:
df_3.dropna(axis=1, thresh=2)

     C1   C3
A   NaN  107
B  78.0   88
C  44.0   67

In [72]:
df_3.fillna('Miss')

     C1    C2   C3
A  Miss  23.0  107
B  78.0  Miss   88
C  44.0  Miss   67